export const data =[
    {post1: require('./imgs/1.jpg'),
        post2 : 'The Perfect Sandwich, A Real NYC Classic',
        post3:'Just some random text, lorem ipsum text praesent tincidunt ipsum lipsum.',
        post4:'150 $'
    },
    {post1: require('./imgs/2.jpg'),
        post2 : 'Let Me Tell You About This Steak',
        post3:'Once again, some random text to lorem lorem lorem lorem ipsum text praesent tincidunt ipsum lipsum.',
        post4:'200 $'},
        {post1: require('./imgs/3.jpg'),
        post2 : 'Cherries, interrupted',
        post3:'Lorem ipsum text praesent tincidunt ipsum lipsum.What else?',
        post4:'620 $'},
        {post1: require('./imgs/4.jpg'),
        post2 : 'Once Again, Robust Wine and Vegetable Pasta',
        post3:'Lorem ipsum text praesent tincidunt ipsum lipsum.',
        post4:'90 $'},
    {post1: require('./imgs/5.jpg'),
        post2 : 'All I Need Is a Popsicle',
        post3:'Lorem ipsum text praesent tincidunt ipsum lipsum.',
        post4:'790 $'},
    {post1: require('./imgs/6.jpg'),
        post2 : 'Salmon For Your Skin',
        post3:'Once again, some random text to lorem lorem lorem lorem ipsum text praesent tincidunt ipsum lipsum.',
        post4:'440 $'},
    {post1: require('./imgs/7.jpg'),
        post2 : 'The Perfect Sandwich, A Real Classic',
        post3:'Just some random text, lorem ipsum text praesent tincidunt ipsum lipsum.',
        post4:'529 $'},
    {post1: require('./imgs/8.jpg'),
        post2 : 'Le French',
        post3:'Lorem lorem lorem lorem ipsum text praesent tincidunt ipsum lipsum.',
        post4:'367 $'},
]